name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
# 1. Run yarn install
      - name: install
        run: yarn install
# 2. When packages installed -> run tests
      - name: test
        run: yarn test
